version: "3"
services:
  jupyter:
    build: .
    volumes:
      - C:\Users\shingo:/tmp/working
    working_dir: /tmp/working
    ports:
      - 8888:8888
    command: jupyter lab --ip=0.0.0.0 --allow-root --no-browser --LabApp.token=''
