FROM gcr.io/kaggle-images/python:v75

RUN pip install -U pip && \
    pip install fastprogress japanize-matplotlib && \
    pip install mlflow && \
    pip install dash && \
    pip install --upgrade tensorflow
