version: "3"
services:
  jupyter:
    build: .
    volumes:
      - C:\Users\shingo\jupyter_notebook\Dockerfiles\kaggle_kernel_jupyter:/tmp/working
    working_dir: /tmp/working
    ports:
      - 8888:8888
    command: jupyter notebook --ip=0.0.0.0 --allow-root --no-browser
